// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MasGlobal.EmployeeWebApi
{
    using Models;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for EmployeeWebApiClient.
    /// </summary>
    public static partial class EmployeeWebApiClientExtensions
    {
        /// <summary>
        /// Gets a list of employees with their data.
        /// </summary>
        /// <param name='operations'>
        /// The operations group for this extension method.
        /// </param>
        public static IList<Employee> ApiEmployeesGet(this IEmployeeWebApiClient operations)
        {
            return Task.Factory.StartNew(s => ((IEmployeeWebApiClient)s).ApiEmployeesGetAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }

        /// <summary>
        /// Gets a list of employees with their data.
        /// </summary>
        /// <param name='operations'>
        /// The operations group for this extension method.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        public static async Task<IList<Employee>> ApiEmployeesGetAsync(this IEmployeeWebApiClient operations, CancellationToken cancellationToken = default(CancellationToken))
        {
            using (var _result = await operations.ApiEmployeesGetWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
            {
                return _result.Body;
            }
        }
    }
}